
---
title: "05s-TryBuildingModel"
output:
  html_document:
    toc: true
---


#Try it out on your own
## Build a Decision Tree and Random Forest - Compare both models

```{r}
%r
# install.packages("e1071")
```


```{r}
#packages

library(randomForest)
library(rpart)
library(caret)
# library(e1071)
```


```{r}
%r

#load my data
# Data Source: https://archive.ics.uci.edu/ml/machine-learning-databases/car/

# Load the dataset and explore
data1 <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data", header = TRUE)
 

```


```{r}
display(head(data1))

#display(class(data1))
```


```{r}
class(data1)
colnames(data1) <- c("BuyingPrice", "Maintenance","NumDoors","NumPersons", "BootSpace","Safety","Condition")

```


```{r}
head(data1)
 

```


```{r}
str(data1)
```


```{r}
summary(data1)
```


```{r}
# head(data1)
# str(data1)

# Split into Train and Validation sets
# Training Set : Validation Set = 70 : 30 (random)
set.seed(100)
train <- sample(nrow(data1), 0.7*nrow(data1), replace = FALSE)
TrainSet <- data1[train,]
ValidSet <- data1[-train,]
summary(TrainSet)

```


```{r}
summary(ValidSet)
```


```{r}
# Create a Random Forest model with default parameters
model1 <- randomForest(Condition ~ ., data = TrainSet, importance = TRUE)
model1
```


```{r}
# Fine tuning parameters of Random Forest model
model2 <- randomForest(Condition ~ ., data = TrainSet, ntree = 500, mtry = 6, importance = TRUE)
model2

```


```{r}
# Predicting on train set
predTrain <- predict(model2, TrainSet, type = "class")
# Checking classification accuracy
table(predTrain, TrainSet$Condition)  
```


```{r}
# Predicting on Validation set
predValid <- predict(model2, ValidSet, type = "class")
# Checking classification accuracy
mean(predValid == ValidSet$Condition)                    

```


```{r}
table(predValid,ValidSet$Condition)
```


```{r}
importance(model2) 
```


```{r}
%r

# To check important variables
# importance(model2)        
varImpPlot(model2)  
```


```{r}
%r

# Using For loop to identify the right mtry for model
a=c()
i=5
for (i in 3:8) {
  model3 <- randomForest(Condition ~ ., data = TrainSet, ntree = 500, mtry = i, importance = TRUE)
  predValid <- predict(model3, ValidSet, type = "class")
  a[i-2] = mean(predValid == ValidSet$Condition)
}
 
a
 
plot(3:8,a)
```


```{r}
summary(TrainSet)
```


```{r}
library(rpart)
library(caret)
library(e1071)
```


```{r}
# We will compare model 1 of Random Forest with Decision Tree model
 
model_dt = train(Condition ~ ., data = TrainSet, method = "rpart")
# model_dt =rpart(Condition ~ ., data = TrainSet,method = "class")
model_dt_1 = predict(model_dt, data = TrainSet)

class(model_dt)

```


```{r}
table(model_dt_1, TrainSet$Condition)
```


```{r}
mean(model_dt_1 == TrainSet$Condition)
```


```{r}
%r
# Running on Validation Set
model_dt_vs = predict(model_dt, newdata = ValidSet)
table(model_dt_vs, ValidSet$Condition)
 

```


```{r}
mean(model_dt_vs == ValidSet$Condition)
```


```{r}
confusionMatrix(model_dt_vs, ValidSet$Condition)
```


```{r}
library("rpart.plot")
rpart.plot(model_dt)
```


```{r}
plot(model_dt$finalModel)
text(model_dt$finalModel)
```


```{r}

```

